name: ESP32 Build Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IDF_PATH: ${{ github.workspace }}/esp-idf  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and ESP-IDF
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          git clone --recursive https://github.com/espressif/esp-idf.git esp-idf
          cd esp-idf
          ./install.sh && . ./export.sh

      - name: Set target to ESP32 and Build
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32
          idf.py build
        working-directory: .
